name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Gzip
        run: |
          tar -zcvf ./lottery-wheel-${{ github.ref_name }}.tar.gz dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./lottery-wheel-${{ github.ref_name }}.tar.gz